web.port: 8080

twilio {

  accounts: [
    {
      name: "maciek"
      sid: ""
      phone: "+48514642718"
      sid: ${?TWILIO_SID_MACIEK}
      secret: ""
      secret: ${?TWILIO_SECRET_MACIEK}
    },
    {
      name: "andrzej"
      sid: ""
      phone: "+48508515833"
      sid: ${?TWILIO_SID_ANDRZEJ}
      secret: ""
      secret: ${?TWILIO_SECRET_ANDRZEJ}
    }
  ]

  enabled = ["maciek", "andrzej"]

}

mqttClientPrefix = ""

notification {
  enabled = true
}

alertzy {
  accountIds = ["6eeacd1is25ay56"]
}